### Recomendaciones para Usuario 1 (Luis)
GET http://localhost:5050/api/v1/recommendations/top3/luis@example.com
Content-Type: application/json

### Recomendaciones para Usuario 2 (Ana)
GET http://localhost:5050/api/v1/recommendations/top3/ana@example.com
Content-Type: application/json

### Recomendaciones para Usuario 3 (Pedro)
GET http://localhost:5050/api/v1/recommendations/top3/pedro@example.com
Content-Type: application/json

### Recomendaciones para Usuario 4 (Camila)
GET http://localhost:5050/api/v1/recommendations/top3/camila@example.com
Content-Type: application/json

### Recomendaciones para Usuario 5 (Marco)
GET http://localhost:5050/api/v1/recommendations/top3/marco@example.com
Content-Type: application/json

### Recomendaciones para Usuario 6 (Lucía)
GET http://localhost:5050/api/v1/recommendations/top3/lucia@example.com
Content-Type: application/json

### Recomendaciones para Usuario 7 (Carlos)
GET http://localhost:5050/api/v1/recommendations/top3/carlos@example.com
Content-Type: application/json

### Recomendaciones para Usuario 8 (Daniela)
GET http://localhost:5050/api/v1/recommendations/top3/daniela@example.com
Content-Type: application/json

### Recomendaciones para Usuario 9 (Iván)
GET http://localhost:5050/api/v1/recommendations/top3/ivan@example.com
Content-Type: application/json

### Recomendaciones para Usuario 10 (Andrea)
GET http://localhost:5050/api/v1/recommendations/top3/andrea@example.com
Content-Type: application/json