GET http://localhost:5050/api/v1/recommendations?correo=carlos@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations?correo=ana@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations?correo=pedro@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations?correo=camila@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations?correo=diego@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations?correo=mateo@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations?correo=valentina@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations?correo=sofia@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations?correo=juan@example.com
Content-Type: application/json