GET http://localhost:5050/api/v1/recommendations/top3/carlos.ramirez1@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/lucia.gomez2@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/mariana.lopez3@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/andres.martinez4@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/valeria.mendoza5@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/pedro.reyes6@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/sofia.cruz7@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/david.castillo8@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/ana.morales9@example.com
Content-Type: application/json

GET http://localhost:5050/api/v1/recommendations/top3/luis.navarro10@example.com
Content-Type: application/json