  ### Usuario 1
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Luis",
  "apellido": "Ramírez",
  "correo": "luis@example.com",
  "contraseña": "luis123",
  "juegos_favoritos": ["Halo Infinite", "FIFA 23"],
  "juegos_interesados": ["Minecraft", "Cyberpunk 2077"],
  "amigos": ["ana@example.com", "pedro@example.com"]
}

### Usuario 2
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Ana",
  "apellido": "Gómez",
  "correo": "ana@example.com",
  "contraseña": "ana456",
  "juegos_favoritos": ["Minecraft", "Skyrim"],
  "juegos_interesados": ["Halo Infinite", "The Witcher 3"],
  "amigos": ["luis@example.com", "camila@example.com"]
}

### Usuario 3
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Pedro",
  "apellido": "López",
  "correo": "pedro@example.com",
  "contraseña": "pedro789",
  "juegos_favoritos": ["The Witcher 3", "Cyberpunk 2077"],
  "juegos_interesados": ["FIFA 23", "Rocket League"],
  "amigos": ["luis@example.com", "marco@example.com"]
}

### Usuario 4
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Camila",
  "apellido": "Torres",
  "correo": "camila@example.com",
  "contraseña": "camila321",
  "juegos_favoritos": ["Apex Legends", "Rocket League"],
  "juegos_interesados": ["Gran Turismo 7", "Call of Duty: Modern Warfare II"],
  "amigos": ["ana@example.com", "lucia@example.com"]
}

### Usuario 5
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Marco",
  "apellido": "Méndez",
  "correo": "marco@example.com",
  "contraseña": "marco777",
  "juegos_favoritos": ["FIFA 23", "Rocket League"],
  "juegos_interesados": ["Apex Legends", "Skyrim"],
  "amigos": ["pedro@example.com", "carlos@example.com"]
}

### Usuario 6
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Lucía",
  "apellido": "Fernández",
  "correo": "lucia@example.com",
  "contraseña": "lucia987",
  "juegos_favoritos": ["Cyberpunk 2077", "Call of Duty: Modern Warfare II"],
  "juegos_interesados": ["The Witcher 3", "Minecraft"],
  "amigos": ["camila@example.com", "daniela@example.com"]
}

### Usuario 7
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Carlos",
  "apellido": "Pérez",
  "correo": "carlos@example.com",
  "contraseña": "carlos159",
  "juegos_favoritos": ["Gran Turismo 7", "Rocket League"],
  "juegos_interesados": ["FIFA 23", "Halo Infinite"],
  "amigos": ["marco@example.com", "ivan@example.com"]
}

### Usuario 8
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Daniela",
  "apellido": "Morales",
  "correo": "daniela@example.com",
  "contraseña": "dani321",
  "juegos_favoritos": ["Skyrim", "The Witcher 3"],
  "juegos_interesados": ["Cyberpunk 2077", "Apex Legends"],
  "amigos": ["lucia@example.com", "andrea@example.com"]
}

### Usuario 9
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Iván",
  "apellido": "Castillo",
  "correo": "ivan@example.com",
  "contraseña": "ivan654",
  "juegos_favoritos": ["Apex Legends", "Call of Duty: Modern Warfare II"],
  "juegos_interesados": ["Rocket League", "Gran Turismo 7"],
  "amigos": ["carlos@example.com", "andrea@example.com"]
}

### Usuario 10
POST http://localhost:5050/api/v1/users
Content-Type: application/json

{
  "nombre": "Andrea",
  "apellido": "Cruz",
  "correo": "andrea@example.com",
  "contraseña": "andrea147",
  "juegos_favoritos": ["Minecraft", "Halo Infinite"],
  "juegos_interesados": ["Skyrim", "FIFA 23"],
  "generos_favoritos": ["Acción", "Aventura"],
  "amigos": ["daniela@example.com", "ivan@example.com"]
}

